version: '3.8'
services:
  frontend:
    container_name: frontend-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      cms-network:
        ipv4_address: 10.0.10.1
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

networks:
  cms-network:
    external: true
