import '../globals.css'
import { Inter } from 'next/font/google'

import { ApolloWrapper } from '@/ApolloWrapper'
import { Aside, Footer, Header } from '@/components/portal'
import { CategoriesProvider, RoutesProvider } from '@/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// const client = new ApolloClient({
//   uri: 'http://localhost:3001/graphql',
//   cache: new InMemoryCache(),
// })

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <CategoriesProvider>
            <RoutesProvider>
              <div className="flex flex-col mx-auto max-w-[1200px] min-h-screen">
                <Header />
                <div className="grid grow md:grid-cols-[70%_30%] gap-5 m-4 overflow-hidden">
                  <main>{children}</main>
                  <Aside />
                </div>
                <Footer />
              </div>
            </RoutesProvider>
          </CategoriesProvider>
        </ApolloWrapper>
      </body>
    </html>
  )
}
