import './globals.css'

import { LoginProvider } from '@/context/LoginProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen grid place-content-center">
        <LoginProvider>
          <div className="bg-white shadow-2xl p-5 rounded-lg min-w-[350px]">{children}</div>
        </LoginProvider>
      </body>
    </html>
  )
}
