import './globals.css'

import { LoginProvider } from '@/context/LoginProvider'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <body className="grid min-h-screen place-content-center">
      <LoginProvider>
        <div className="min-w-[350px] rounded-lg bg-white p-5 shadow-2xl">{children}</div>
      </LoginProvider>
    </body>
  )
}
